---
name: Validate - Gradle Wrapper

on:
  pull_request:

permissions:
  contents: read

jobs:
  validate-gradle:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
